fairpay_user_registration_step1:
    path:     /register/{token}/step1
    defaults: { _controller: FairpayUserBundle:Registration:step1 }

fairpay_user_registration_step2:
    path:     /register/{token}/step2
    defaults: { _controller: FairpayUserBundle:Registration:step2 }

fairpay_user_registration_step3:
    path:     /register/{token}/step3
    defaults: { _controller: FairpayUserBundle:Registration:step3 }