services:
    user_manager:
        class: Fairpay\Bundle\UserBundle\Manager\UserManager
        arguments:
            - "@security.password_encoder"
            - "@fairpay.token_generator"
            - "@fairpay.string_util"
        calls:
            - [ init,[ "@doctrine.orm.entity_manager", "@event_dispatcher" ] ]
            - [ setSchoolManager,[ "@school_manager" ] ]

    user_provider:
        class: Fairpay\Bundle\UserBundle\Security\UserProvider
        arguments:
            - "@user_manager"

    api_authenticator:
        class: Fairpay\Bundle\UserBundle\Security\ApiAuthenticator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@jwt_generator"
            - "@user_manager"
            - "@school_manager"

    jwt_generator:
        class: Fairpay\Bundle\UserBundle\Security\JwtGenerator
        arguments:
            - "%base_host%"
            - "%secret%"
            - "@school_manager"

    # Tiwg
    fairpay.twig.api_token_extension:
        class: Fairpay\Bundle\UserBundle\Twig\ApiTokenExtension
        arguments:
            - "@jwt_generator"
            - "@security.token_storage"
        tags:
            - { name: twig.extension }

    # Validator

    validator.fairpay.display_name:
        class: Fairpay\Bundle\UserBundle\Validator\Constraints\DisplayNameValidator
        arguments:
            - "@fairpay.string_util"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.display_name }