services:
    user_manager:
        class: Fairpay\Bundle\UserBundle\Manager\UserManager
        arguments:
            - "@security.password_encoder"
            - "@fairpay.token_generator"
            - "@fairpay.string_util"
        calls:
            - [ init,[ "@doctrine.orm.entity_manager", "@event_dispatcher" ] ]
            - [ setSchoolManager,[ "@school_manager" ] ]

    user_provider:
        class: Fairpay\Bundle\UserBundle\Security\UserProvider
        arguments:
            - "@user_manager"

    # Validator

    validator.fairpay.display_name:
        class: Fairpay\Bundle\UserBundle\Validator\Constraints\DisplayNameValidator
        arguments:
            - "@fairpay.string_util"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.display_name }