services:
    user_manager:
        class: Fairpay\Bundle\UserBundle\Manager\UserManager
        arguments:
            - "@security.password_encoder"
            - "@fairpay.token_generator"
            - "@fairpay.string_util"
            - "@security.token_storage"
            - "@token_manager"
        calls:
            - [ init,[ "@doctrine.orm.entity_manager", "@event_dispatcher" ] ]
            - [ setSchoolManager,[ "@school_manager" ] ]

    token_manager:
        class: Fairpay\Bundle\UserBundle\Manager\TokenManager
        arguments:
            - "@fairpay.token_generator"
        calls:
            - [ init,[ "@doctrine.orm.entity_manager", "@event_dispatcher" ] ]

    user_provider:
        class: Fairpay\Bundle\UserBundle\Security\UserProvider
        arguments:
            - "@user_manager"

    api_authenticator:
        class: Fairpay\Bundle\UserBundle\Security\ApiAuthenticator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@jwt_generator"
            - "@user_manager"
            - "@school_manager"

    virtual_user_authenticator:
        class: Fairpay\Bundle\UserBundle\Security\VirtualUserAuthenticator

    jwt_generator:
        class: Fairpay\Bundle\UserBundle\Security\JwtGenerator
        arguments:
            - "%base_host%"
            - "%secret%"
            - "@school_manager"

    token_param_converter:
        class: Fairpay\Bundle\UserBundle\Request\ParamConverter\TokenParamConverter
        arguments:
            - "@token_manager"
            - "@school_manager"
        tags:
            - { name: request.param_converter }

    # Tiwg
    fairpay.twig.api_token_extension:
        class: Fairpay\Bundle\UserBundle\Twig\ApiTokenExtension
        arguments:
            - "@jwt_generator"
            - "@security.token_storage"
        tags:
            - { name: twig.extension }

    # Validator

    validator.fairpay.display_name:
        class: Fairpay\Bundle\UserBundle\Validator\Constraints\DisplayNameValidator
        arguments:
            - "@fairpay.string_util"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.display_name }


    # Listener

    fairpay.user.email_listener:
        class: Fairpay\Bundle\UserBundle\EventListener\EmailListener
        calls:
            - [ init,[ "@mailer", "@twig" ] ]
        tags:
            - { name: kernel.event_subscriber }