fairpay_student_list:
    path:     /admin/students
    defaults: { _controller: FairpayStudentBundle:Admin:list }

fairpay_student_add:
    path:     /admin/students/add
    defaults: { _controller: FairpayStudentBundle:Admin:add }