services:
    student_manager:
        class: Fairpay\Bundle\StudentBundle\Manager\StudentManager
        arguments:
            - "@security.token_storage"
        calls:
            - [ init,[ "@doctrine.orm.entity_manager", "@event_dispatcher" ] ]
            - [ setSchoolManager,[ "@school_manager" ] ]

    student_param_converter:
        class: Fairpay\Bundle\StudentBundle\Request\ParamConverter\StudentParamConverter
        arguments:
            - "@student_manager"
        tags:
            - { name: request.param_converter }