services:
    student_manager:
        class: Fairpay\Bundle\StudentBundle\Manager\StudentManager
        calls:
            - [ init,[ "@doctrine.orm.entity_manager", "@event_dispatcher" ] ]
            - [ setSchoolManager,[ "@school_manager" ] ]