imports:
    - { resource: config_dev.yml }

parameters:
    base_host: localhost

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:     pdo_sqlite
        host:       localhost
        charset:    UTF8
        path:       "%kernel.root_dir%/../var/cache/sqlite.db.cache"

security:
    firewalls:
        school:
            guard:
                authenticators:
                    - virtual_user_authenticator