# Public

fairpay_showcase:
    resource: "@FairpayShowcaseBundle/Resources/config/routing.yml"
    host: %base_host%
    prefix:   /

fairpay_school_registration:
    resource: "@FairpaySchoolBundle/Resources/config/registration.yml"
    host: %base_host%
    prefix:   /

# API

fairpay_student_api:
    resource: "@FairpayStudentBundle/Resources/config/api.yml"
    host: api.%base_host%


# School

fairpay_security:
    resource: "@FairpayUserBundle/Resources/config/security.yml"
    host: "{_subdomain}.%base_host%"
    prefix:   /

fairpay_user_registration:
    resource: "@FairpayUserBundle/Resources/config/registration.yml"
    host: "{_subdomain}.%base_host%"
    prefix:   /

fairpay_student_public:
    resource: "@FairpayStudentBundle/Resources/config/public.yml"
    host: "{_subdomain}.%base_host%"
    prefix:   /

fairpay_student_admin:
    resource: "@FairpayStudentBundle/Resources/config/admin.yml"
    host: "{_subdomain}.%base_host%"
    prefix:   /