fairpay_showcase:
    resource: "@FairpayShowcaseBundle/Resources/config/routing.yml"
    host: %base_host%
    prefix:   /

fairpay_registration:
    resource: "@FairpaySchoolBundle/Resources/config/registration.yml"
    host: %base_host%
    prefix:   /