fairpay_showcase:
    resource: "@FairpayShowcaseBundle/Resources/config/routing.yml"
    host: %base_host%
    prefix:   /

fairpay_registration:
    resource: "@FairpaySchoolBundle/Resources/config/registration.yml"
    host: %base_host%
    prefix:   /

fairpay_security:
    resource: "@FairpayUserBundle/Resources/config/security.yml"
    host: "{_subdomain}.%base_host%"
    prefix:   /

fairpay_student_admin:
    resource: "@FairpayStudentBundle/Resources/config/admin.yml"
    host: "{_subdomain}.%base_host%"
    prefix:   /admin/students