security:
    encoders:
        Fairpay\Bundle\UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        fairpay_db:
            id: user_provider

    role_hierarchy:
        ROLE_STUDENTS_MANAGE : ROLE_USER
        ROLE_SUBSCRIBERS_MANAGE : ROLE_USER
        ROLE_SETTINGS_MANAGE : ROLE_USER
        ROLE_ADMIN_MANAGE : ROLE_USER
        ROLE_EVENT_MANAGE : ROLE_USER

        ROLE_ACCOUNTS_VIEW : ROLE_USER
        ROLE_ACCOUNTS_MANAGE : ROLE_ACCOUNTS_VIEW

        ROLE_VENDOR_VIEW : ROLE_USER
        ROLE_VENDOR_MANAGE : ROLE_VENDOR_VIEW

        ROLE_TRANSACTION_VIEW : ROLE_USER
        ROLE_TRANSACTION_DEPOSIT : ROLE_TRANSACTION_VIEW
        ROLE_TRANSACTION_WITHDRAWAL : ROLE_TRANSACTION_DEPOSIT
        ROLE_TRANSACTION_VENDOR : ROLE_TRANSACTION_WITHDRAWAL
        ROLE_TRANSACTION_GOD : ROLE_TRANSACTION_VENDOR

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        showcase:
            host: ^(www\.)?%base_host%$
            stateless: true
            anonymous: ~

        api:
            host: ^api\.%base_host%$
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - api_authenticator

        school:
            host: ^[^.]+\.%base_host%$
            anonymous: true
            form_login:
                provider: fairpay_db
                csrf_token_generator: security.csrf.token_manager
            logout: ~

    access_control:
        - { path: ^/login$, host: ^[^.]+\.%base_host%$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, host: ^[^.]+\.%base_host%$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, host: ^[^.]+\.%base_host%$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, host: ^[^.]+\.%base_host%$, role: ROLE_USER }