security:
    encoders:
        Fairpay\Bundle\UserBundle\Security\UserProvider:
            algorithm: bcrypt

    providers:
        fairpay_db:
            id: user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        showcase:
            host: ^(www\.)?%base_host%$
            stateless: true
            anonymous: ~

        api:
            host: ^api\.%base_host%$
            stateless: true
            anonymous: ~

        school:
            host: ^[^.]+\.%base_host%$
            anonymous: ~

