security:
    encoders:
        Fairpay\Bundle\UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        fairpay_db:
            id: user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        showcase:
            host: ^(www\.)?%base_host%$
            stateless: true
            anonymous: ~

        api:
            host: ^api\.%base_host%$
            stateless: true
            anonymous: ~

        school:
            host: ^[^.]+\.%base_host%$
            anonymous: true
            form_login:
                provider: fairpay_db
                csrf_token_generator: security.csrf.token_manager
            logout: ~

    access_control:
        - { path: ^/login$, host: ^[^.]+\.%base_host%$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, host: ^[^.]+\.%base_host%$, role: ROLE_USER }