fairpay_student_list:
    path:     /admin/students
    defaults: { _controller: FairpayStudentBundle:Admin:list }

fairpay_student_add:
    path:     /admin/students/add
    defaults: { _controller: FairpayStudentBundle:Admin:add }

fairpay_student_edit:
    path:     /admin/students/{id}/edit
    defaults: { _controller: FairpayStudentBundle:Admin:edit }
    requirements:
        id: \d+|b80bb7740288fda1f201890375a60c8f

fairpay_student_create_user:
    path:     /admin/students/{id}/create-account
    defaults: { _controller: FairpayStudentBundle:Admin:createUser }
    requirements:
        id: \d+|b80bb7740288fda1f201890375a60c8f