<?php

namespace Fairpay\Bundle\VendorBundle\Repository;

/**
 * RoleGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
