<?php

namespace Fairpay\Bundle\VendorBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fairpay\Bundle\UserBundle\Entity\User;
use Fairpay\Bundle\VendorBundle\Entity\Group;

/**
 * RoleGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleGroupRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param User $vendor
     * @return Group|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByUserAndVendor(User $user, User $vendor)
    {
        return $this->createQueryBuilder('g')
            ->where('g.vendor = :vendor')
            ->andWhere('g.users = :onlyOne OR g.users LIKE :first OR g.users LIKE :last OR g.users LIKE :middle')
            ->setParameters([
                'onlyOne' => $user->getId(),
                'first'   => $user->getId() . ',%',
                'last'    => '%,' . $user->getId(),
                'middle'  => '%,' . $user->getId() . ',%',
                'vendor'  => $vendor,
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
