parameters:
    email.standard:
            - aol
            - att
            - comcast
            - email
            - facebook
            - fastmail
            - free
            - games
            - gmail
            - gmx
            - google
            - googlemail
            - hotmail
            - hush
            - hushmail
            - icloud
            - inbox
            - laposte
            - lavabit
            - live
            - love
            - mac
            - mail
            - me
            - msn
            - neuf
            - orange
            - outlook
            - pobox
            - rocketmail
            - safe-mail
            - sbcglobal
            - sfr
            - verizon
            - wanadoo
            - wow
            - yahoo
            - ygm
            - ymail
            - zoho