<?php

namespace Fairpay\Bundle\StudentBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function queryAll()
    {
        return $this->createQueryBuilder('s');
    }
}
