<?php

namespace Fairpay\Bundle\StudentBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Fairpay\Bundle\SchoolBundle\Entity\School;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param School $school
     * @return QueryBuilder
     */
    public function queryAll(School $school)
    {
        return $this->createQueryBuilder('s')
            ->where('s.school = :school')
            ->setParameter('school', $school)
            ;
    }
}
