<?php

namespace Fairpay\Bundle\StudentBundle\Repository;

/**
 * SubHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
