services:
    fairpay.email_helper:
        class: Fairpay\Util\Email\Services\EmailHelper
        arguments:
            - %email.disposable%
            - %email.standard%

    fairpay.token_generator:
        class: Fairpay\Util\Util\TokenGenerator

    fairpay.string_util:
        class: Fairpay\Util\Util\StringUtil

    fairpay.paginator:
        class: Fairpay\Util\Pagination\Paginator
        arguments:
            - "@router"

    # Tiwg
    fairpay.twig.html_extension:
        class: Fairpay\Util\Twig\HtmlExtension
        arguments:
            - "@router"
        tags:
            - { name: twig.extension }

    fairpay.twig.formatter_extension:
        class: Fairpay\Util\Twig\FormatterExtension
        arguments:
            - "@translator"
        tags:
            - { name: twig.extension }

    # Listeners

    fairpay.exception_listener:
        class: Fairpay\Util\EventListener\ExceptionListener
        arguments:
            - "%base_host%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    fairpay.api_view_listener:
        class: Fairpay\Util\EventListener\ApiViewListener
        arguments:
            - "@jms_serializer"
            - "%base_host%"
        tags:
            - { name: kernel.event_subscriber }

    # Validators

    validator.fairpay.unique_entity:
        class: Fairpay\Util\Validator\Constraints\UniqueEntityValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.unique_entity }

    validator.fairpay.not_disposable_email:
        class: Fairpay\Util\Email\Validator\Constraints\NotDisposableEmailValidator
        arguments:
            - "@fairpay.email_helper"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.not_disposable_email }

    validator.fairpay.not_standard_email:
        class: Fairpay\Util\Email\Validator\Constraints\NotStandardEmailValidator
        arguments:
            - "@fairpay.email_helper"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.not_standard_email }

    validator.fairpay.valid_domain:
        class: Fairpay\Util\Email\Validator\Constraints\ValidDomainValidator
        arguments:
            - "@fairpay.email_helper"
        tags:
            - { name: validator.constraint_validator, alias: fairpay.valid_domain }
