<?php

namespace Fairpay\Bundle\SchoolBundle\Repository;

use Fairpay\Bundle\SchoolBundle\Entity\School;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithOldSlug($oldSlug)
    {
        $result = $this->createQueryBuilder('s')
            ->where('s.oldSlugs LIKE :slug')
            ->setParameter('slug', "%$oldSlug%")
            ->getQuery()
            ->getResult();

        return array_filter($result, function($school) use($oldSlug) {
            /** @var School $school */
            return in_array($oldSlug, $school->getOldSlugs());
        });
    }
}
