fairpay_school_registration_step1:
    path:     /register/{registrationToken}/1
    defaults: { _controller: FairpaySchoolBundle:Registration:step1 }

fairpay_school_registration_step2:
    path:     /register/{registrationToken}/2
    defaults: { _controller: FairpaySchoolBundle:Registration:step2 }