services:
    school_manager:
        class: Fairpay\Bundle\SchoolBundle\Manager\SchoolManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    fairpay.school.email_listener:
        class: Fairpay\Bundle\SchoolBundle\EventListener\EmailListener
        arguments:
            - "@mailer"
            - "@twig"
        tags:
            - { name: kernel.event_subscriber }